kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsbatches.ayushanand.live
spec:
  group: ayushanand.live
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevOpsBatch
    shortNames:
      - portfolio
      - resume
      - email
  scope: Namespaced
  versions: 
  - name: v1
    served: true
    storage: true 
    schema: 
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
                description: "Email of the student"
              resume:
                type: string
                description: "Resume of the student"
              portfolio:
                type: string
                description: "Portfolio of the student"