apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx  # here we are creating the pods in nginx namespace
spec:
    containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"  # Minimum memory the container will get
            cpu: "250m"     # Minimum CPU the container will get
          limits:
            memory: "128Mi" # Maximum memory the container can use
            cpu: "500m"     # Maximum CPU the container can use
    tolerations:
      - key: "prod"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"